import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Card, Form, Button } from 'react-bootstrap';


export default function Home() {
  return (
    <>
      <Head>
        <title>SameTune</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <Card  style={{ width:"20em" }}>
          <Card.Body>
            <Card.Title>SameTune</Card.Title>
            <Form.Control type='text' id='playlistCode' placeholder='Insira o código de hub :D' />
            <Button>Ou crie um novo hub</Button>
          </Card.Body>
        </Card>
        
      </main>
    </>
  )
}
